### ISSUE TITLE
Recovery build fails withdocker option

### ISSUE THREAD

**Issue by nimaim** [angeloc/br-template#1]
I know this is very old so apologies. Commenting back in the recovery lines in br-template.config and building with "make withdocker all" yields this error:

```
make[1]: Leaving directory '/home/br-user/out/qemu_arm_versatile_custom'
BR2_DL_DIR=/home/br-user/out/dl BR2_JLEVEL=20 \
	make -C out/qemu_arm_versatile_custom_recovery source all
make[1]: Entering directory '/home/br-user/out/qemu_arm_versatile_custom_recovery'
for f in board/qemu/arm-versatile/linux-4.13.config ; do if [ ! -f "${f}" ]; then printf "Kconfig fragment '%s' for '%s' does not exist\n" "${f}" "linux"; exit 1; fi; done
make[2]: *** [linux/linux.mk:607: board/qemu/arm-versatile/linux-4.13.config] Error 1
Kconfig fragment 'board/qemu/arm-versatile/linux-4.13.config' for 'linux' does not exist
make[1]: *** [Makefile:23: _all] Error 2
make[1]: Leaving directory '/home/br-user/out/qemu_arm_versatile_custom_recovery'
make: *** [Makefile:51: image] Error 2
make: *** [Makefile:87: withdocker] Error 2
```

The qemu_arm_versatile_custom board images all seem to be built okay just prior.

Another question, do you have example files of how to achieve the update scheme you outlined in your Linuxlab Conf talk with a redundant bootloader and recovery partition? The "official" swupdate docs all point to a traditional A/B double copy scheme of just having a copy of rootfs. We'd like to update the entire system (including U-boot bootloader) and thus far your proposal sounds best but I am not sure how to implement it without a full example. Thanks!

**Comment by angeloc** [comment]
> The qemu_arm_versatile_custom board images all seem to be built okay just prior.

You should use withdocker or not. If you mix compiling with and without, there will be some paths problems.

> Another question, do you have example files of how to achieve the update scheme you outlined in your Linuxlab Conf talk with 
> a redundant bootloader and recovery partition? The "official" swupdate docs all point to a traditional A/B double copy scheme of 
> just having a copy of rootfs. We'd like to update the entire system (including U-boot bootloader) and thus far your proposal
> sounds best but I am not sure how to implement it without a full example. Thanks!

Yeah, basically, if you double the bootloader also, you need some method to choose which bootloader to boot from. In the presentation, I highlighted some ways to do that. What you require is a spl with the correct compile flags enabled to be able to select the bootloader based on an env variable. You need also some uboot scripting to select the proper kernel and build an appropriate kernel commandline which points to the correct rootfs.
So it requires a bit of work to be implemented. Every pointer should be in the presentation btw.

If you need some professional support, you can contact my company at info@amarulasolutions.com

**Comment by angeloc** [comment]
diff --git a/buildroot-external/configs/qemu_arm_versatile_custom_recovery_defconfig b/buildroot-external/configs/qemu_arm_versatile_custom_recovery_defconfig
```
index 57efe42..1a2139c 100644
--- a/buildroot-external/configs/qemu_arm_versatile_custom_recovery_defconfig
+++ b/buildroot-external/configs/qemu_arm_versatile_custom_recovery_defconfig
@@ -13,7 +13,7 @@ BR2_LINUX_KERNEL=y
 BR2_LINUX_KERNEL_CUSTOM_VERSION=y
 BR2_LINUX_KERNEL_CUSTOM_VERSION_VALUE="4.13.3"
 BR2_LINUX_KERNEL_USE_CUSTOM_CONFIG=y
-BR2_LINUX_KERNEL_CUSTOM_CONFIG_FILE="board/qemu/arm-versatile/linux-4.13.config"
+BR2_LINUX_KERNEL_CUSTOM_CONFIG_FILE="board/qemu/arm-versatile/linux.config"
 BR2_LINUX_KERNEL_DTS_SUPPORT=y
 BR2_LINUX_KERNEL_INTREE_DTS_NAME="versatile-pb"
 BR2_PACKAGE_SWUPDATE=y
```
This should solve your error
